---
- id: header_check
  name: header_check
  entry: header_check
  language: golang
  types_or: [objective-c, objective-c++, swift, swiftdeps, java, go, c, c++]
  description: Analyze and update header for copyright and licensing
  args: [--owner "Karl Kraft", --autodate, --license, arr]
  pass_filenames: true
