---
name: Build
permissions:
  contents: read

on:                          # yamllint disable-line rule:truthy
  schedule:
    - cron: '34 08 * * 6'

  workflow_dispatch:

  push:
    branches-ignore:
      - 'update/**'
      - 'dependabot/**'
    tags:
      - '**'

jobs:

  macOS:
    runs-on:
      - self-hosted
      - macOS

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: macOS GO Build
        run: $HOME/github/bin/build_go_macos.sh

      - name: Mark Completed
        run: touch  ${{ runner.temp }}/Green

  linux:
    strategy:
      matrix:
        include:
          - arch: x86-64
            runner: X64
          - arch: arm64
            runner: ARM64

    runs-on:
      - self-hosted
      - linux
      - ${{ matrix.runner }}

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Linux GO Build
        run: $HOME/github/bin/build_go_linux.sh

      - name: Mark Completed
        run: touch  ${{ runner.temp }}/Green
